### ISSUE TITLE
Discord Server?

### ISSUE THREAD

**Issue by 7quit** [Xenthys/ShareXen#16]
Hi,

I would have a lot of questions about ShareXen, but the Discord Invite Link doesn't seem to exist any more, I would be happy if you could send me a new one, so I can ask a lot of questions.

ps: Or you can contact me by Discord: urito#0001

**Comment by Xenthys** [comment]
Hello, the Discord invite was indeed tied to an old non-profit which is no longer active, I therefore deleted the Discord server itself and moved on then forgot to update it here. You may join [ShareX](https://discord.gg/ShareX) per example where we can discuss in the off-topic channel. If it becomes necessary to move to my personal server, we'll see there and then, thank you!

I'll close this issue once I've updated the README regarding the Discord server.
