### ISSUE TITLE
Deleting files with admin token does not work

### ISSUE THREAD

**Issue by IceroDev** [Xenthys/ShareXen#19]
Hi, deleting with domain.tld/sharexen.php?endpoint=delete&tojen=TOKEN&filename=ojehjohouvzr.png
Where TOKEN is a token from a user that is in the admin array won't work.

It says that user is missing permissions while it is in the admin array. 

Did I made a mistake ?

Sincerely,
Jean Staffe

**Comment by Xenthys** [comment]
Bonjour Jean,

En effet, le token d'authentification ne peut être précisé que par le biais d'une requête POST en tant que champ de formulaire ou JSON, il n'est pas possible de le spécifier en paramètre GET (indépendamment du mode de requête) pour des raisons de sécurité, seuls les jetons de suppression générés lors de l'upload d'une image sont supportés.

L'erreur de permissions est par conséquent une erreur d'authentification, essaie plutôt avec curl ou Postman par exemple !

Cordialement,
Dylan
