### ISSUE TITLE
Might require some changes on ShareXen.sxcu

### ISSUE THREAD

**Issue by justiceserv** [Xenthys/ShareXen#22]
The file that is currently on GitHub returns the wrong url output. (My server is Debian 11 Bullseye, PHP 7.4, client is windows 10.)
Current: 
`﻿{
  "Version": "14.0.0",
  "DestinationType": "ImageUploader",
  "RequestMethod": "POST",
  "RequestURL": "https://your.domain/sharexen.php",
  "Body": "MultipartFormData",
  "Arguments": {
    "endpoint": "upload",
    "token": "change-me"
  },
  "FileFormName": "image",
  "URL": "{json:url}",
  "DeletionURL": "{json:deletion_url}",
  "ErrorMessage": "{json:error_msg}"
}` 
-> This copies {json:url} to clipboard. 

Change: 
`
{
  "Version": "14.0.0",
  "DestinationType": "ImageUploader",
  "RequestMethod": "POST",
  "RequestURL": "",
  "Body": "MultipartFormData",
  "Arguments": {
    "endpoint": "upload",
    "token": ""
  },
  "FileFormName": "image",
  "URL": "$json:url$",
  "DeletionURL": "$json:deletion_url$",
  "ErrorMessage": "$json:error_msg$"
}
`
-> This returns the expected URL.

**Comment by Jaex** [comment]
You should update your ShareX to latest version.
