### ISSUE TITLE
500 Internal Error

### ISSUE THREAD

**Issue by IchiiDev** [Xenthys/ShareXen#5]
Hi, I tried to install the last version of ShareXen and change the config constants from it. But when i try to upload an image with ShareX the API send me this error code:
`Status code:
(500) Internal Server Error

Headers:
Connection: keep-alive
Content-Encoding: none
Content-Length: 233
Content-Type: application/json; charset=utf-8
Date: Tue, 22 Oct 2019 18:22:44 GMT
Server: nginx/1.14.2

Response text:
{"api_version":"2.3.1","api_source":"https:\/\/github.com\/Xenthys\/ShareXen","endpoint":"upload","username":"Ichii","iteration_count":1,"error":"upload_failed","http_code":500,"status":"error","execution_time":0.0006890296936035156}

Stack trace:
   à System.Net.HttpWebRequest.GetResponse()
   à ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)`

I tried everything and double checked the config contants but nothing to do, it send every time an error code 500.

Can you help me ?
Ichii

**Comment by Xenthys** [comment]
Bonjour, je vais répondre en français.

Cette erreur est causée lorsque le script n'est pas capable d'écrire dans le dossier où il se situe. À en juger par l'utilisation de NGINX, je suppose que PHP-FPM est derrière, et que l'utilisateur faisant tourner le processus est capable de lire le contenu du dossier mais pas d'y écrire des fichiers. Il faut donc modifier l'utilisateur qui exécute PHP-FPM, ou changer les droits sur le dossier dans lequel le script se trouve.

**Comment by IchiiDev** [comment]
Bonjour, 

Effectivement, après avoir passé le dossier en permission 777 il a réussi à upload !
Je te remercie ^^ Bonne journée à toi

Cordialement,
Ichii
