### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by ririko5834** [Xenthys/ShareXen#8]
Can you please add option to use Discord RichEmbeds for Discord webhook logging?

**Comment by Xenthys** [comment]
Hmm, in all honesty it doesn't seem to be very useful for logging. It's going to take more space in the target channel without bringing in more information.

That being said, it's trivial to implement so I don't really mind. Do you have any idea about the format you would like to see or whatever is fine?

**Comment by ririko5834** [comment]
Its OK

**Comment by ririko5834** [comment]
My another feature request is: 
- Create endpoint stats for ADMINS that can show you how many files were uploaded, total used storage space and free space,  list of file url, file size and deletion url (so admins can easily check files and delete files if they want)

**Comment by Xenthys** [comment]
The requested "stats" endpoint is called "info" and is already available, returning more information to admins than users.

Deletion URLs aren't necessary for admins since they can already delete images without needing the secret key.

Disk usage should be monitored at a higher level and won't be implemented.

**Comment by ririko5834** [comment]
How can i delete image without secret key?  And how can i get list of all files?

**Comment by Xenthys** [comment]
Please check the README, this is a documented API. You need to perform POST calls on the required endpoints, where you have to provide your token like you do for an upload along with any other parameter if necessary.

**Comment by ririko5834** [comment]
What online tool can i use for POST requests?

**Comment by ririko5834** [comment]
Anoher suggestion:
- Add config option to upload images to custom folder

**Comment by jzeuzs** [comment]
> What online tool can i use for POST requests?

postman?

**Comment by Xenthys** [comment]
Per-user folders moved to their own issue (#12), closing this one which is too generic and stalled.
