### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ririko5834** [Xenthys/ShareXen#9]
Hi my online FTP file manager is showing me:
![image](https://user-images.githubusercontent.com/64729293/92989663-03135a00-f4d6-11ea-9b48-c966e0da368e.png)

**Comment by Xenthys** [comment]
Your editor is failing to parse the file correctly, or incorrectly considers whatever it understands as an error. Open an issue with them, this doesn't cause any error with ShareXen itself, thank you.

**Comment by ririko5834** [comment]
ok

**Comment by ririko5834** [comment]
Logs are working: 
![image](https://user-images.githubusercontent.com/64729293/92989867-baf53700-f4d7-11ea-8cd8-5871352cda8d.png)
